/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as GovernmentRouteImport } from './routes/government'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as Investigation2024RouteImport } from './routes/investigation-2024'
import { Route as NewsroomRouteImport } from './routes/newsroom'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as TaxRouteImport } from './routes/tax'
import { Route as VarietiesRouteImport } from './routes/varieties'
import { Route as Watch2026RouteImport } from './routes/watch-2026'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernmentRoute = GovernmentRouteImport.update({
  id: '/government',
  path: '/government',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const Investigation2024Route = Investigation2024RouteImport.update({
  id: '/investigation-2024',
  path: '/investigation-2024',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsroomRoute = NewsroomRouteImport.update({
  id: '/newsroom',
  path: '/newsroom',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxRoute = TaxRouteImport.update({
  id: '/tax',
  path: '/tax',
  getParentRoute: () => rootRouteImport,
} as any)
const VarietiesRoute = VarietiesRouteImport.update({
  id: '/varieties',
  path: '/varieties',
  getParentRoute: () => rootRouteImport,
} as any)
const Watch2026Route = Watch2026RouteImport.update({
  id: '/watch-2026',
  path: '/watch-2026',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/explorer': typeof ExplorerRoute
  '/government': typeof GovernmentRoute
  '/history': typeof HistoryRoute
  '/investigation-2024': typeof Investigation2024Route
  '/newsroom': typeof NewsroomRoute
  '/sources': typeof SourcesRoute
  '/tax': typeof TaxRoute
  '/varieties': typeof VarietiesRoute
  '/watch-2026': typeof Watch2026Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/explorer': typeof ExplorerRoute
  '/government': typeof GovernmentRoute
  '/history': typeof HistoryRoute
  '/investigation-2024': typeof Investigation2024Route
  '/newsroom': typeof NewsroomRoute
  '/sources': typeof SourcesRoute
  '/tax': typeof TaxRoute
  '/varieties': typeof VarietiesRoute
  '/watch-2026': typeof Watch2026Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/explorer': typeof ExplorerRoute
  '/government': typeof GovernmentRoute
  '/history': typeof HistoryRoute
  '/investigation-2024': typeof Investigation2024Route
  '/newsroom': typeof NewsroomRoute
  '/sources': typeof SourcesRoute
  '/tax': typeof TaxRoute
  '/varieties': typeof VarietiesRoute
  '/watch-2026': typeof Watch2026Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/explorer'
    | '/government'
    | '/history'
    | '/investigation-2024'
    | '/newsroom'
    | '/sources'
    | '/tax'
    | '/varieties'
    | '/watch-2026'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/explorer'
    | '/government'
    | '/history'
    | '/investigation-2024'
    | '/newsroom'
    | '/sources'
    | '/tax'
    | '/varieties'
    | '/watch-2026'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/explorer'
    | '/government'
    | '/history'
    | '/investigation-2024'
    | '/newsroom'
    | '/sources'
    | '/tax'
    | '/varieties'
    | '/watch-2026'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ExplorerRoute: typeof ExplorerRoute
  GovernmentRoute: typeof GovernmentRoute
  HistoryRoute: typeof HistoryRoute
  Investigation2024Route: typeof Investigation2024Route
  NewsroomRoute: typeof NewsroomRoute
  SourcesRoute: typeof SourcesRoute
  TaxRoute: typeof TaxRoute
  VarietiesRoute: typeof VarietiesRoute
  Watch2026Route: typeof Watch2026Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/government': {
      id: '/government'
      path: '/government'
      fullPath: '/government'
      preLoaderRoute: typeof GovernmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigation-2024': {
      id: '/investigation-2024'
      path: '/investigation-2024'
      fullPath: '/investigation-2024'
      preLoaderRoute: typeof Investigation2024RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsroom': {
      id: '/newsroom'
      path: '/newsroom'
      fullPath: '/newsroom'
      preLoaderRoute: typeof NewsroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax': {
      id: '/tax'
      path: '/tax'
      fullPath: '/tax'
      preLoaderRoute: typeof TaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/varieties': {
      id: '/varieties'
      path: '/varieties'
      fullPath: '/varieties'
      preLoaderRoute: typeof VarietiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch-2026': {
      id: '/watch-2026'
      path: '/watch-2026'
      fullPath: '/watch-2026'
      preLoaderRoute: typeof Watch2026RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ExplorerRoute: ExplorerRoute,
  GovernmentRoute: GovernmentRoute,
  HistoryRoute: HistoryRoute,
  Investigation2024Route: Investigation2024Route,
  NewsroomRoute: NewsroomRoute,
  SourcesRoute: SourcesRoute,
  TaxRoute: TaxRoute,
  VarietiesRoute: VarietiesRoute,
  Watch2026Route: Watch2026Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()